# Generated by Django 5.0.6 on 2024-07-04 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0004_notification_patientid'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('age', models.IntegerField(max_length=5)),
                ('gender', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=20)),
                ('sample_type', models.CharField(max_length=50)),
                ('hemoglobin', models.FloatField()),
                ('range', models.CharField(max_length=100)),
                ('prescription', models.TextField(blank=True)),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.appointment')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app2.patient')),
            ],
        ),
    ]
