# Generated by Django 5.0.6 on 2024-07-04 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0006_report_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='lab_name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='report',
            name='test_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
