# Generated by Django 5.0.6 on 2024-07-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0007_report_lab_name_report_test_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='report_pdf',
            field=models.FileField(null=True, upload_to='reports/'),
        ),
    ]
