# Generated by Django 5.0.6 on 2024-07-05 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0008_report_report_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_pdf',
            field=models.FileField(blank=True, null=True, upload_to='reports/'),
        ),
    ]
