# Generated by Django 5.0.6 on 2024-07-05 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app2', '0009_alter_report_report_pdf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='report_pdf',
            field=models.FileField(default=None, max_length=250, null=True, upload_to='reports/'),
        ),
    ]
